### ISSUE TITLE
Failed tests don't fail the build

### ISSUE THREAD

**Issue by bergie** [jdavis/grunt-cafe-mocha#1]
Currently having failed Mocha tests don't abort the build, which means cafemocha doesn't make CIs like Travis report failures:

```
✖ 1 of 106 tests failed:

 1) Network with a simple graph should contain two nodes:
TypeError: Cannot read property 'processes' of null
 at Context.<anonymous> (/home/bergie/Projects/noflo/noflo/spec/Network.coffee:87:20)
 at Test.Runnable.run (/home/bergie/Projects/noflo/noflo/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runnable.js:213:32)
 at Runner.runTest (/home/bergie/Projects/noflo/noflo/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:344:10)
 at Runner.runTests.next (/home/bergie/Projects/noflo/noflo/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:390:12)
 at next (/home/bergie/Projects/noflo/noflo/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:270:14)
 at Runner.hooks (/home/bergie/Projects/noflo/noflo/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:279:7)
 at next (/home/bergie/Projects/noflo/noflo/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:227:23)
 at Runner.hook (/home/bergie/Projects/noflo/noflo/node_modules/grunt-cafe-mocha/node_modules/mocha/lib/runner.js:247:5)
 at process.startup.processNextTick.process._tickCallback (node.js:244:9)


Done, without errors.
```

**Comment by jdavis** [comment]
That's definitely a problem. I'll take a look at this as soon as I can, thanks a lot Henri.

**Comment by jdavis** [comment]
@bergie Hey Henri, I think I fixed the issue of the failing test not failing the build. Now Grunt should be notified of any Mocha failures. Let me know if you have any more issues. I've bumped the version to 0.1.2 and have updated NPM as well. Here's the latest commit for reference, b8378a495fd2c9581f972aeb966233f2a3fcc36c.

**Comment by bentruyman** [comment]
Was just about to file this bug. Upgraded to 0.1.2, everything's working well. Thanks for this @bergie and @jdavis!

**Comment by jdavis** [comment]
Awesome, glad it works for you, @bentruyman!
